### PR TITLE
Added caretLine method

### PR DESCRIPTION
**Pull request by krasnoukhov**
Returns current line number for actual caret position

### CODE REVIEW

**Comment by lukemorton** [comment]
Thanks for the pull request, sorry it's taken me so long to get back to you!

Just wondering what uses you had for this function and how you see it fitting into the scope of this project?

**Comment by krasnoukhov** [comment]
@DrPheltRight I've implemented simple text editor for editing tree structure, which displays line numbers. Just thought that may be helpful for someone.

**Comment by maxwellaguiarsilva** [comment]
dont show when select with caret plugin if the text is overflow input!
how do this?
Sorry my english, i am brasilian

**Comment by lukemorton** [comment]
@maxwellaguiarsilva Feel free to create a new issue with an example of the problem :)

**Comment by maxwellaguiarsilva** [comment]
http://www.maxwellupload.xpg.com.br/mascara/mask.htm

**Pull request closed without merging**
